Import all important ML and data science things 

In [3]:
import torch
import pandas as pd
import numpy as py
import matplotlib as plt


C:\Users\Michael\AppData\Local\Temp\ipykernel_12104\3705802748.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


CREATING TENSORS AND SEEING THEIR ATTRIBUTES


In [25]:

scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.item())
print(scalar.size())


0
7
torch.Size([])


In [27]:
vector = torch.tensor([3,2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([3, 2])
1
torch.Size([2])


In [32]:
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [31]:

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
