Import all important ML and data science things 

In [11]:
import torch
import pandas as pd
import numpy as py
import matplotlib as plt
import torchvision
from torchvision import transforms, datasets
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)


CREATING TENSORS AND SEEING THEIR ATTRIBUTES


In [25]:

scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.item())
print(scalar.size())


0
7
torch.Size([])


In [27]:
vector = torch.tensor([3,2])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([3, 2])
1
torch.Size([2])


In [32]:
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [27]:

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


Creating random tensors as well as zeros and ones tensors

In [44]:
random_tensor = torch.rand(3,2)

print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)
print(random_tensor.dtype)


tensor([[0.3521, 0.1757],
        [0.8436, 0.7169],
        [0.5972, 0.6814]])
torch.Size([3, 2])
2
torch.float32


In [46]:
zeros = torch.zeros(size=(3,4))
print(zeros)
print(zeros.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])


In [30]:
ones =torch.ones(size=(3,4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


MAKING ARRAY OF WITH ARANGE

In [34]:
onetoten = torch.arange(1,11)
print(onetoten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [36]:
tenzeros = torch.zeros_like(input=onetoten)
print(tenzeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [39]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype =None,
                                device = None,
                                requires_grad = False)
print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)


torch.Size([3])
torch.float32
cpu


In [40]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = torch.float16,
                               )
print(float_16_tensor.dtype)

torch.float16


MANIPUALTING TENSORS

In [54]:
#Adding
tensor = torch.tensor([2,2,3])
print(tensor + 10)


tensor([12, 12, 13])


In [55]:
#Minus
print(tensor - 10)


tensor([-8, -8, -7])


In [60]:
print(torch.add(tensor,10))

tensor([12, 12, 13])


In [61]:
print(tensor * tensor)

tensor([4, 4, 9])


In [62]:
print(torch.matmul(tensor,tensor))

tensor(17)


In [63]:
 
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)



In [64]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [5]:
x = torch.Tensor([2,1])
x


tensor([2., 1.])

In [6]:
y = torch.rand([2,5])
y

tensor([[0.5073, 0.0054, 0.6445, 0.4002, 0.1560],
        [0.2257, 0.8444, 0.5152, 0.9883, 0.5901]])

In [7]:
y.view([1,10])

tensor([[0.5073, 0.0054, 0.6445, 0.4002, 0.1560, 0.2257, 0.8444, 0.5152, 0.9883,
         0.5901]])

In [8]:
y = y.view([1,10])

In [9]:
y

tensor([[0.5073, 0.0054, 0.6445, 0.4002, 0.1560, 0.2257, 0.8444, 0.5152, 0.9883,
         0.5901]])